/**
 * Sujets des catégories de lancement (H-3). Chaque sujet désigne un article de
 * fr.wikipedia ; l'image retenue est l'image principale de l'élément Wikidata
 * (propriété P18), hébergée sur Wikimedia Commons.
 *
 * § 4.1, vigilance : on écarte les œuvres dont l'auteur est mort depuis moins de
 * 70 ans (Christ Rédempteur, Atomium, pyramide du Louvre, Opéra de Sydney…).
 * `group` : sujets confondables, jamais réunis dans un même tirage (EF-3.9).
 */

export interface Subject {
  article: string;
  /** Titre affiché, par défaut l'article sans précision entre parenthèses. */
  title?: string;
  group?: string;
  /**
   * Fichier Commons imposé, à la place de l'image principale Wikidata quand celle-ci se prête mal
   * au jeu (sujet trop petit dans le cadre, panorama, gravure parmi des photographies).
   */
  file?: string;
}

export interface SubjectList {
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
  subjects: Subject[];
}

export const SUBJECT_LISTS: SubjectList[] = [
  {
    slug: 'monuments',
    name: 'Monuments',
    description: 'Monuments emblématiques du monde entier, des pyramides aux cathédrales.',
    sortOrder: 1,
    subjects: [
      { article: 'Tour Eiffel' },
      { article: 'Colisée' },
      { article: 'Taj Mahal' },
      { article: 'Grande Muraille', title: 'Grande Muraille de Chine' },
      { article: 'Pyramide de Khéops' },
      { article: 'Grand Sphinx de Gizeh' },
      { article: 'Machu Picchu' },
      { article: 'Chichén Itzá', group: 'pyramide-mesoamericaine' },
      { article: 'Pyramide du Soleil', title: 'Pyramide du Soleil (Teotihuacan)', group: 'pyramide-mesoamericaine' },
      { article: 'Angkor Vat' },
      { article: 'Parthénon' },
      { article: 'Statue de la Liberté' },
      { article: 'Big Ben' },
      { article: 'Tower Bridge' },
      { article: 'Porte de Brandebourg' },
      { article: 'Cathédrale Saint-Basile-le-Bienheureux', title: 'Cathédrale Saint-Basile' },
      { article: 'Sainte-Sophie (Constantinople)', title: 'Sainte-Sophie' },
      { article: 'Tour de Pise' },
      { article: 'Basilique Saint-Pierre' },
      { article: 'Fontaine de Trevi' },
      { article: 'Cathédrale Notre-Dame de Paris', title: 'Notre-Dame de Paris', group: 'cathedrale-gothique' },
      { article: 'Cathédrale de Cologne', group: 'cathedrale-gothique' },
      { article: 'Cathédrale de Milan', group: 'cathedrale-gothique' },
      { article: "Arc de triomphe de l'Étoile", title: 'Arc de triomphe' },
      { article: 'Mont-Saint-Michel' },
      { article: 'Château de Versailles', group: 'palais-baroque' },
      { article: 'Château de Schönbrunn', group: 'palais-baroque' },
      { article: 'Château de Chambord', group: 'chateau-renaissance' },
      { article: 'Château de Chenonceau', group: 'chateau-renaissance' },
      { article: 'Pont du Gard' },
      { article: 'Basilique du Sacré-Cœur de Montmartre', title: 'Sacré-Cœur de Montmartre' },
      { article: 'Château de Neuschwanstein' },
      { article: 'Alhambra (Grenade)', title: 'Alhambra' },
      { article: 'Stonehenge' },
      { article: 'Al-Khazneh', title: 'Al-Khazneh (Pétra)' },
      { article: "Temples d'Abou Simbel", title: 'Abou Simbel' },
      { article: 'Temple de Karnak' },
      { article: 'Cité interdite' },
      { article: 'Temple du Ciel' },
      { article: 'Borobudur' },
      { article: 'Moaï', title: 'Moaï de l’île de Pâques' },
      { article: 'Kinkaku-ji' },
      { article: 'Château de Himeji' },
      { article: 'Itsukushima-jinja', title: 'Sanctuaire d’Itsukushima' },
      { article: 'Palais du Potala' },
      { article: 'Pagode Shwedagon' },
      { article: 'Harmandir Sahib', title: 'Temple d’Or d’Amritsar' },
      { article: 'Qutb Minar' },
      { article: 'Hawa Mahal' },
      { article: 'Wat Arun' },
      { article: 'Tikal' },
      { article: 'Grande mosquée de Djenné' },
      { article: 'Bete Giyorgis', title: 'Église Saint-Georges de Lalibela' },
      // Image principale Wikidata : un panorama, trop bas une fois réduit ; vue d'ensemble à la place.
      { article: 'Cité de Carcassonne', file: 'Carcassonne La Cité Vue n°3.jpg' },
      { article: 'Palais des papes d\'Avignon', title: 'Palais des papes' },
      { article: 'Abbaye de Westminster' },
      { article: "Château d'Édimbourg" },
      { article: 'Pont Charles' },
      { article: 'Parlement hongrois' },
      { article: 'Tour de Belém' },
      { article: 'Aqueduc de Ségovie' },
      { article: 'Mosquée-cathédrale de Cordoue' },
      { article: 'Palais des Doges' },
      { article: 'Pont du Rialto' },
      { article: 'Cathédrale Santa Maria del Fiore', title: 'Cathédrale de Florence' },
      { article: 'Capitole des États-Unis' },
      { article: 'Maison-Blanche' },
      { article: 'Golden Gate Bridge' },
      { article: 'Château Frontenac' },
      { article: 'Persépolis' },
      { article: 'Régistan (Samarcande)', title: 'Régistan de Samarcande' },
      { article: 'Dôme du Rocher' },
      { article: 'Chrysler Building' },
      { article: 'Tour de Londres' },
    ],
  },
  {
    slug: 'histoire',
    name: 'Histoire',
    description: 'Personnages, œuvres et objets qui ont marqué l’histoire.',
    sortOrder: 2,
    subjects: [
      { article: 'La Joconde' },
      { article: 'Vénus de Milo', group: 'statue-marbre' },
      { article: 'Victoire de Samothrace' },
      { article: 'Pierre de Rosette' },
      { article: 'Masque funéraire de Toutânkhamon', title: 'Masque de Toutânkhamon' },
      { article: 'Buste de Néfertiti' },
      { article: 'Tapisserie de Bayeux' },
      { article: 'Armée de terre cuite' },
      { article: 'Code de Hammurabi' },
      { article: 'Grotte de Lascaux' },
      { article: 'Vénus de Willendorf' },
      { article: 'Discobole' },
      { article: 'Groupe du Laocoon', title: 'Laocoon' },
      { article: 'David (Michel-Ange)', title: 'David de Michel-Ange', group: 'statue-marbre' },
      { article: 'Casque de Sutton Hoo' },
      { article: 'Figurines de Lewis', title: 'Pièces d’échecs de Lewis' },
      { article: 'La Liberté guidant le peuple' },
      { article: 'Le Radeau de La Méduse' },
      { article: 'Bonaparte franchissant le Grand-Saint-Bernard', group: 'napoleon' },
      { article: 'Le Sacre de Napoléon', group: 'napoleon' },
      { article: 'Napoléon dans son cabinet de travail', group: 'napoleon' },
      { article: 'La Cène (Léonard de Vinci)', title: 'La Cène' },
      { article: "La Création d'Adam" },
      { article: 'La Jeune Fille à la perle' },
      { article: 'La Ronde de nuit' },
      { article: 'La Nuit étoilée (1889)', title: 'La Nuit étoilée' },
      { article: 'La Naissance de Vénus (Botticelli)', title: 'La Naissance de Vénus' },
      { article: "L'École d'Athènes" },
      { article: 'Les Ménines' },
      { article: 'Tres de mayo', title: 'Tres de mayo (Goya)' },
      { article: 'La Grande Vague de Kanagawa' },
      { article: 'Le Cri' },
      { article: 'Magna Carta' },
      { article: 'Bible de Gutenberg' },
      { article: 'Livre de Kells' },
      { article: "Machine d'Anticythère" },
      { article: 'Disque céleste de Nebra' },
      { article: "Porte d'Ishtar" },
      { article: "Étendard d'Ur" },
      { article: 'Têtes colossales olmèques' },
      { article: 'Pierre du Soleil', title: 'Pierre du Soleil aztèque' },
      { article: "Masque d'Agamemnon" },
      { article: 'Aurige de Delphes' },
      { article: 'Louve du Capitole' },
      { article: 'Auguste de Prima Porta', group: 'statue-marbre' },
      { article: 'Portrait de Louis XIV en costume de sacre', title: 'Louis XIV en costume de sacre' },
      { article: "Le Portrait de l'Armada", title: 'Élisabeth Ire (portrait de l’Armada)' },
      { article: "Jeanne d'Arc au sacre du roi Charles VII", title: 'Jeanne d’Arc (Ingres)' },
      { article: 'Portrait de Marie-Antoinette à la rose', title: 'Marie-Antoinette à la rose' },
      { article: 'George Washington (Lansdowne Portrait)', title: 'George Washington (portrait Lansdowne)' },
      { article: 'Abraham Lincoln' },
      { article: 'Victoria (reine du Royaume-Uni)', title: 'Reine Victoria' },
      { article: 'Albert Einstein' },
      { article: 'Marie Curie' },
      { article: 'Mohandas Karamchand Gandhi', title: 'Gandhi' },
      { article: 'Léonard de Vinci' },
      { article: 'Galilée (savant)', title: 'Galilée' },
      { article: 'Isaac Newton' },
      { article: 'William Shakespeare' },
      { article: 'Molière' },
      { article: 'Victor Hugo' },
      { article: 'Wolfgang Amadeus Mozart', title: 'Mozart' },
      { article: 'Ludwig van Beethoven', title: 'Beethoven' },
      { article: "Mosaïque d'Alexandre" },
      { article: "Bateau d'Oseberg" },
      { article: 'Liberty Bell', title: 'Cloche de la Liberté' },
      { article: 'Couronne de saint Édouard' },
      { article: 'Enigma (machine)', title: 'Machine Enigma' },
      { article: 'Wright Flyer' },
      { article: 'Titanic (paquebot)', title: 'Titanic' },
      { article: "La Déclaration d'indépendance (Trumbull)", title: 'La Déclaration d’indépendance (Trumbull)' },
    ],
  },
  {
    slug: 'faune',
    name: 'Faune',
    description: 'Animaux des cinq continents et des océans.',
    sortOrder: 4,
    subjects: [
      { article: 'Lion' },
      { article: 'Tigre' },
      { article: 'Léopard', group: 'felin-tachete' },
      { article: 'Jaguar', group: 'felin-tachete' },
      { article: 'Guépard', group: 'felin-tachete' },
      { article: "Éléphant de savane d'Afrique", title: 'Éléphant d’Afrique' },
      { article: 'Girafe' },
      { article: 'Zèbre des plaines', title: 'Zèbre' },
      { article: 'Rhinocéros blanc' },
      { article: 'Hippopotame amphibie', title: 'Hippopotame' },
      { article: 'Gorille' },
      { article: 'Chimpanzé commun', title: 'Chimpanzé' },
      { article: 'Orang-outan' },
      { article: 'Kangourou roux', title: 'Kangourou' },
      { article: 'Koala' },
      { article: 'Panda géant' },
      { article: 'Petit panda' },
      { article: 'Flamant rose' },
      { article: 'Paon bleu', title: 'Paon' },
      { article: 'Pygargue à tête blanche' },
      { article: 'Harfang des neiges' },
      { article: 'Toucan toco', title: 'Toucan' },
      { article: 'Ara macao' },
      { article: 'Colibri à gorge rubis', title: 'Colibri' },
      { article: 'Macareux moine' },
      { article: "Autruche d'Afrique", title: 'Autruche' },
      { article: 'Manchot empereur' },
      { article: 'Grand dauphin', title: 'Dauphin' },
      { article: 'Orque' },
      { article: 'Baleine à bosse' },
      { article: 'Grand requin blanc', title: 'Requin blanc' },
      { article: 'Tortue verte', title: 'Tortue marine' },
      // Image principale Wikidata : une gravure, seule parmi des photographies.
      {
        article: 'Poulpe commun',
        title: 'Pieuvre',
        file: 'Pulpo (Octopus vulgaris), isla de Mouro, Santander, España, 2019-08-14, DD 30.jpg',
      },
      { article: 'Amphiprion ocellaris', title: 'Poisson-clown' },
      { article: 'Hippocampe (poisson)', title: 'Hippocampe' },
      { article: 'Caméléon panthère', title: 'Caméléon' },
      { article: 'Crocodile du Nil', title: 'Crocodile' },
      { article: 'Dragon de Komodo' },
      { article: 'Rainette aux yeux rouges' },
      // Image principale Wikidata : serpent trop petit dans le cadre pour une carte ; tête en gros plan.
      { article: 'Cobra royal', file: 'Ophiophagus hannah head.jpg' },
      { article: 'Tortue géante des Galápagos' },
      { article: 'Dromadaire' },
      { article: 'Lama (animal)', title: 'Lama' },
      { article: "Bison d'Amérique", title: 'Bison' },
      { article: 'Élan', title: 'Élan (orignal)', group: 'cervide' },
      { article: 'Renne', group: 'cervide' },
      { article: 'Loup gris', title: 'Loup' },
      { article: 'Renard roux', group: 'renard' },
      { article: 'Renard polaire', group: 'renard' },
      { article: 'Raton laveur' },
      { article: "Hérisson d'Europe", title: 'Hérisson' },
      { article: 'Écureuil roux' },
      { article: "Castor d'Europe", title: 'Castor' },
      { article: 'Bradypus variegatus', title: 'Paresseux à trois doigts', group: 'paresseux' },
      { article: 'Tatou à neuf bandes', title: 'Tatou' },
      { article: 'Ornithorynque' },
      { article: 'Suricate' },
      { article: 'Maki catta' },
      { article: 'Monarque (papillon)', title: 'Papillon monarque' },
      { article: 'Abeille européenne', title: 'Abeille' },
      { article: 'Coccinelle à sept points', title: 'Coccinelle' },
      { article: 'Ours brun' },
      { article: 'Ours blanc' },
      { article: 'Morse (animal)', title: 'Morse' },
      { article: 'Loutre de mer' },
      { article: 'Lynx boréal', title: 'Lynx' },
      { article: 'Axolotl' },
      { article: 'Paresseux à deux doigts', title: 'Paresseux à deux doigts', group: 'paresseux' },
      { article: 'Chouette effraie', title: 'Chouette effraie' },
      { article: 'Pélican brun', title: 'Pélican' },
      { article: 'Mouffette rayée', title: 'Mouffette' },
    ],
  },
  {
    slug: 'espace',
    name: 'Espace',
    description: 'Planètes, lunes, nébuleuses, galaxies et missions spatiales, en images de la NASA, de l’ESA et de Commons.',
    sortOrder: 5,
    subjects: [
      { article: 'Soleil' },
      { article: 'Mercure (planète)', group: 'astre-cratere' },
      { article: 'Vénus (planète)' },
      { article: 'Terre' },
      { article: 'Mars (planète)' },
      { article: 'Jupiter (planète)' },
      { article: 'Saturne (planète)' },
      { article: 'Uranus (planète)', group: 'geante-de-glace' },
      { article: 'Neptune (planète)', group: 'geante-de-glace' },
      { article: 'Pluton (planète naine)' },
      { article: 'Cérès (planète naine)', group: 'astre-cratere' },
      { article: 'Lune', group: 'astre-cratere' },
      { article: 'Io (lune)' },
      { article: 'Europe (lune)', group: 'lune-glacee' },
      { article: 'Ganymède (lune)', group: 'lune-glacee' },
      { article: 'Callisto (lune)', group: 'astre-cratere' },
      { article: 'Titan (lune)' },
      { article: 'Encelade (lune)', group: 'lune-glacee' },
      { article: 'Phobos (lune)' },
      { article: 'Grande Tache rouge' },
      { article: 'Olympus Mons' },
      { article: 'Valles Marineris' },
      { article: 'Comète de Halley', group: 'comete' },
      { article: 'C/1995 O1 (Hale-Bopp)', title: 'Comète Hale-Bopp', group: 'comete' },
      { article: 'Aurore polaire' },
      { article: 'Éclipse solaire' },
      { article: 'Meteor Crater' },
      { article: 'Voie lactée' },
      { article: 'Galaxie d’Andromède', group: 'galaxie-spirale' },
      { article: 'Galaxie du Tourbillon', group: 'galaxie-spirale' },
      { article: 'Galaxie du Triangle', group: 'galaxie-spirale' },
      { article: 'Galaxie du Sombrero' },
      { article: 'Grand Nuage de Magellan' },
      { article: 'Quintette de Stephan' },
      { article: 'Pléiades (astronomie)', title: 'Pléiades' },
      { article: 'Omega Centauri', title: 'Oméga du Centaure' },
      { article: 'Nébuleuse du Crabe' },
      { article: 'Nébuleuse d’Orion', group: 'nebuleuse-diffuse' },
      { article: 'Piliers de la création' },
      { article: 'Nébuleuse de la Carène', group: 'nebuleuse-diffuse' },
      { article: 'Nébuleuse de la Tête de Cheval' },
      { article: 'Nébuleuse de la Rosette', group: 'nebuleuse-diffuse' },
      { article: "Nébuleuse de l'Hélice", title: 'Nébuleuse de l’Hélice', group: 'nebuleuse-planetaire' },
      { article: "Nébuleuse de l'Œil de chat", title: 'Nébuleuse de l’Œil de chat', group: 'nebuleuse-planetaire' },
      { article: 'Nébuleuse de la Lyre', group: 'nebuleuse-planetaire' },
      { article: 'Cassiopeia A' },
      { article: 'Sagittarius A*', title: 'Trou noir de la Voie lactée' },
      { article: 'La Bille bleue', title: 'La Bille bleue (Apollo 17)' },
      { article: 'Lever de Terre' },
      { article: 'Spoutnik 1' },
      { article: 'Vostok 1' },
      { article: 'Apollo 11' },
      { article: 'Module lunaire Apollo' },
      { article: 'Lunar Roving Vehicle', title: 'Jeep lunaire', group: 'rover' },
      // Image principale Wikidata : sept fusées côte à côte, illisibles sur une carte ; un seul décollage.
      { article: 'Saturn V', group: 'fusee', file: 'Apollo 11 Launch - GPN-2000-000630.jpg' },
      { article: 'Ariane 5', group: 'fusee' },
      { article: 'Falcon 9', group: 'fusee' },
      { article: 'Navette spatiale américaine', title: 'Navette spatiale' },
      { article: 'Station spatiale internationale' },
      { article: 'Mir (station spatiale)', title: 'Station Mir' },
      { article: 'Skylab' },
      { article: 'Télescope spatial Hubble' },
      { article: 'Télescope spatial James-Webb' },
      { article: 'Voyager 1', group: 'sonde' },
      { article: 'Cassini-Huygens', group: 'sonde' },
      { article: 'New Horizons', group: 'sonde' },
      { article: 'Rosetta (sonde spatiale)', title: 'Rosetta', group: 'sonde' },
      { article: 'Curiosity (rover)', title: 'Curiosity', group: 'rover' },
      { article: 'Perseverance (rover)', title: 'Perseverance', group: 'rover' },
      { article: 'Opportunity (rover)', title: 'Opportunity', group: 'rover' },
      { article: 'Iouri Gagarine', title: 'Youri Gagarine' },
      { article: 'Valentina Terechkova' },
      { article: 'Neil Armstrong', group: 'astronaute-apollo' },
      { article: 'Buzz Aldrin', group: 'astronaute-apollo' },
      { article: 'Sally Ride' },
      { article: "Radiotélescope d'Arecibo", title: 'Radiotélescope d’Arecibo' },
      { article: 'Very Large Telescope' },
      { article: 'Centre spatial guyanais' },
    ],
  },
  {
    slug: 'merveilles-naturelles',
    name: 'Merveilles naturelles',
    description: 'Montagnes, chutes, déserts, récifs et volcans : les paysages les plus spectaculaires de la planète.',
    sortOrder: 6,
    subjects: [
      { article: 'Grand Canyon', group: 'canyon-rouge' },
      { article: 'Antelope Canyon', group: 'canyon-rouge' },
      { article: 'Horseshoe Bend', group: 'canyon-rouge' },
      { article: 'Monument Valley', group: 'canyon-rouge' },
      { article: 'Parc national des Arches', title: 'Arches National Park', group: 'canyon-rouge' },
      { article: 'Vallée de la Mort' },
      { article: 'Mont Everest', title: 'Everest', group: 'sommet-enneige' },
      { article: 'K2', group: 'sommet-enneige' },
      { article: 'Cervin', group: 'sommet-enneige' },
      { article: 'Mont Blanc', group: 'sommet-enneige' },
      { article: 'Denali', group: 'sommet-enneige' },
      { article: 'Aconcagua', group: 'sommet-enneige' },
      { article: 'Kilimandjaro' },
      { article: 'Mont Fuji' },
      { article: 'Mont Ararat', title: 'Ararat' },
      { article: 'Mont Roraima' },
      { article: 'Montagne de la Table' },
      { article: 'Mont du Pain de Sucre', title: 'Pain de Sucre' },
      { article: 'Half Dome' },
      { article: 'Wadi Rum' },
      { article: 'Chutes du Niagara', group: 'chute' },
      { article: 'Chutes Victoria', group: 'chute' },
      { article: "Chutes d'Iguazú", title: 'Chutes d’Iguazú', group: 'chute' },
      { article: 'Salto Ángel', group: 'chute' },
      { article: 'Skógafoss', group: 'chute' },
      { article: 'Gullfoss', group: 'chute' },
      { article: "Baie d'Along", title: 'Baie d’Ha Long' },
      { article: 'Uluru' },
      { article: 'Grande Barrière de corail' },
      { article: 'Les Douze Apôtres', group: 'falaise' },
      { article: 'Falaises de Moher', group: 'falaise' },
      { article: "Falaises d'Étretat", title: 'Falaises d’Étretat', group: 'falaise' },
      { article: 'Chaussée des Géants' },
      { article: 'Mer Morte' },
      { article: 'Lac Baïkal' },
      { article: 'Lac Moraine', group: 'lac-de-montagne' },
      { article: 'Crater Lake', group: 'lac-de-montagne' },
      { article: 'Lac Louise', group: 'lac-de-montagne' },
      { article: "Salar d'Uyuni", title: 'Salar d’Uyuni' },
      { article: 'Sahara', group: 'dunes' },
      { article: 'Désert du Namib', title: 'Namib', group: 'dunes' },
      { article: 'Dune du Pilat', group: 'dunes' },
      { article: 'Parc national des Lençóis Maranhenses', title: 'Lençóis Maranhenses', group: 'dunes' },
      { article: 'Sossusvlei', group: 'dunes' },
      { article: 'Milford Sound' },
      { article: 'Lac Titicaca' },
      { article: 'Aoraki/Mont Cook', title: 'Aoraki (mont Cook)', group: 'sommet-enneige' },
      { article: 'Grand Prismatic Spring' },
      { article: 'Old Faithful', group: 'geyser' },
      { article: 'Strokkur', group: 'geyser' },
      { article: 'Pamukkale' },
      { article: 'Cappadoce' },
      { article: 'Gorges du Verdon' },
      { article: 'Cirque de Gavarnie' },
      { article: 'Geirangerfjord' },
      { article: 'Preikestolen' },
      { article: 'Glacier Perito Moreno', group: 'glacier' },
      { article: 'Jökulsárlón', group: 'glacier' },
      { article: 'Parc national Torres del Paine', title: 'Torres del Paine' },
      { article: 'Îles Galápagos' },
      { article: 'Amazone (fleuve)', title: 'Amazone' },
      { article: "Delta de l'Okavango", title: 'Delta de l’Okavango' },
      { article: 'Cratère du Ngorongoro' },
      { article: 'Tsingy de Bemaraha' },
      { article: 'Allée des baobabs' },
      { article: 'Parc forestier national de Zhangjiajie', title: 'Zhangjiajie' },
      { article: 'Rizières de Banaue', title: 'Rizières de Banaue' },
      { article: 'Parc national des lacs de Plitvice', title: 'Lacs de Plitvice' },
      { article: 'Bora-Bora' },
      { article: 'General Sherman (arbre)', title: 'General Sherman (séquoia géant)' },
      { article: 'Etna', group: 'volcan' },
      { article: 'Stromboli', group: 'volcan' },
      { article: 'Vésuve', group: 'volcan' },
      { article: 'Kīlauea', group: 'volcan' },
      { article: 'Piton de la Fournaise', group: 'volcan' },
      { article: 'Eyjafjallajökull', group: 'volcan' },
      { article: 'Krakatoa', group: 'volcan' },
      { article: 'Mont Kinabalu' },
      { article: 'Parc national des Everglades', title: 'Everglades' },
      { article: 'Lofoten' },
      { article: 'Vatnajökull' },
      { article: 'Mont Saint-Elias' },
    ],
  },
  {
    // Œuvres du domaine public, distinctes de celles de la catégorie Histoire (Joconde, Nuit étoilée…).
    slug: 'peinture',
    name: 'Peinture',
    description: 'Chefs-d’œuvre de la peinture, de Van Eyck à Klimt, tous dans le domaine public.',
    sortOrder: 7,
    subjects: [
      { article: 'Les Époux Arnolfini' },
      { article: "Retable de l'Agneau mystique", title: 'L’Agneau mystique' },
      { article: 'Le Jardin des délices' },
      { article: 'La Tour de Babel (Bruegel)', title: 'La Tour de Babel' },
      { article: 'Chasseurs dans la neige' },
      { article: 'Le Repas de noces' },
      { article: 'Le Printemps (Botticelli)', title: 'Le Printemps' },
      { article: "L'Annonciation (Fra Angelico, Madrid)", title: 'L’Annonciation (Fra Angelico)' },
      { article: "La Dame à l'hermine", title: 'La Dame à l’hermine' },
      { article: "Vénus d'Urbin", title: 'Vénus d’Urbin' },
      { article: 'Amour sacré et Amour profane' },
      { article: 'La Tempête (Giorgione)', title: 'La Tempête' },
      { article: 'La Madone Sixtine' },
      { article: 'La Vocation de saint Matthieu' },
      { article: "L'Enterrement du comte d'Orgaz", title: 'L’Enterrement du comte d’Orgaz' },
      { article: 'Vertumne (Arcimboldo)', title: 'Vertumne' },
      { article: 'Les Ambassadeurs' },
      { article: 'Le Lièvre', title: 'Le Lièvre (Dürer)' },
      { article: 'Autoportrait (Dürer, Munich)', title: 'Autoportrait à la fourrure' },
      { article: 'La Laitière' },
      { article: 'Vue de Delft' },
      { article: "La Leçon d'anatomie du docteur Tulp", title: 'La Leçon d’anatomie du docteur Tulp' },
      { article: "Portrait d'Innocent X", title: 'Portrait d’Innocent X' },
      { article: "Les Hasards heureux de l'escarpolette", title: 'L’Escarpolette' },
      { article: 'Saturne dévorant un de ses fils' },
      { article: 'La Maja nue' },
      { article: 'Le Serment des Horaces' },
      { article: 'La Mort de Marat' },
      { article: 'La Grande Odalisque' },
      { article: 'La Mort de Sardanapale' },
      { article: 'Le Voyageur contemplant une mer de nuages' },
      { article: 'La Charrette de foin' },
      { article: 'Pluie, Vapeur et Vitesse' },
      { article: 'Le Dernier Voyage du Téméraire' },
      { article: 'Ophélie (Millais)', title: 'Ophélie' },
      { article: 'The Lady of Shalott (Waterhouse)', title: 'La Dame de Shalott' },
      { article: 'Un enterrement à Ornans' },
      { article: "L'Atelier du peintre", title: 'L’Atelier du peintre' },
      { article: 'Le Désespéré' },
      { article: 'Les Glaneuses' },
      { article: "L'Angélus", title: 'L’Angélus' },
      { article: "Le Déjeuner sur l'herbe", title: 'Le Déjeuner sur l’herbe' },
      { article: 'Olympia (Manet)', title: 'Olympia' },
      { article: 'Le Fifre (Manet)', title: 'Le Fifre' },
      { article: 'Un bar aux Folies Bergère' },
      { article: 'Impression, soleil levant' },
      { article: 'Champ de coquelicots (Monet)', title: 'Les Coquelicots' },
      { article: 'La Promenade (Monet)', title: 'La Femme à l’ombrelle' },
      { article: 'La Gare Saint-Lazare' },
      { article: 'La Grenouillère (Monet)', title: 'La Grenouillère' },
      { article: 'Les Parapluies', title: 'Les Parapluies (Renoir)' },
      { article: "L'Absinthe", title: 'L’Absinthe (Degas)' },
      { article: 'Bal du moulin de la Galette' },
      { article: 'Le Déjeuner des canotiers' },
      { article: 'Rue de Paris, temps de pluie' },
      { article: 'Les Raboteurs de parquet' },
      { article: 'La Classe de danse (Degas, Paris)', title: 'La Classe de danse' },
      { article: 'Le Berceau', title: 'Le Berceau (Morisot)' },
      { article: "Un dimanche après-midi à l'île de la Grande Jatte", title: 'Un dimanche après-midi à l’île de la Grande Jatte' },
      { article: 'Les Joueurs de cartes' },
      { article: 'La Montagne Sainte-Victoire vue de Bellevue', title: 'La Montagne Sainte-Victoire' },
      { article: 'Les Tournesols', group: 'van-gogh-jaune' },
      { article: 'La Chambre de Van Gogh à Arles', title: 'La Chambre à Arles', group: 'van-gogh-jaune' },
      { article: 'Terrasse du café le soir' },
      { article: 'Les Mangeurs de pommes de terre' },
      { article: 'Autoportrait à l’oreille bandée' },
      { article: 'D’où venons-nous ? Que sommes-nous ? Où allons-nous ?', title: 'D’où venons-nous ?' },
      { article: 'Le Rêve (Rousseau)', title: 'Le Rêve' },
      { article: 'La Bohémienne endormie' },
      { article: 'Madame X (Sargent)', title: 'Madame X' },
      { article: 'Arrangement en gris et noir n° 1', title: 'La Mère de Whistler' },
      { article: 'Le Baiser (Klimt)', title: 'Le Baiser', group: 'klimt-or' },
      { article: "Portrait d'Adele Bloch-Bauer I", title: 'Portrait d’Adele Bloch-Bauer I', group: 'klimt-or' },
      { article: 'La Madone (Munch)', title: 'La Madone' },
      { article: 'Le Bain turc (Ingres)', title: 'Le Bain turc' },
      { article: 'Le Fuji par temps clair' },
      { article: 'American Gothic' },
      { article: 'Composition VIII' },
      { article: 'Composition avec grand plan rouge, jaune, noir, gris et bleu' },
    ],
  },
  {
    slug: 'instruments',
    name: 'Instruments de musique',
    description: 'Cordes, vents, percussions et claviers des cinq continents.',
    sortOrder: 8,
    subjects: [
      { article: 'Violon', group: 'famille-violon' },
      { article: 'Alto (instrument de musique)', title: 'Alto', group: 'famille-violon' },
      { article: 'Violoncelle', group: 'famille-violon' },
      { article: 'Contrebasse', group: 'famille-violon' },
      { article: 'Harpe' },
      { article: 'Guitare', group: 'guitare' },
      { article: 'Guitare électrique', group: 'guitare' },
      { article: 'Ukulélé', group: 'guitare' },
      { article: 'Banjo' },
      { article: 'Mandoline', group: 'luth' },
      { article: 'Luth', group: 'luth' },
      { article: 'Oud', group: 'luth' },
      { article: 'Bouzouki', group: 'luth' },
      { article: 'Balalaïka' },
      { article: 'Sitar' },
      { article: 'Koto' },
      { article: 'Guzheng' },
      { article: 'Erhu' },
      { article: 'Kora' },
      { article: 'Balafon', group: 'lames' },
      { article: 'Berimbau' },
      { article: 'Charango' },
      { article: 'Vielle à roue' },
      { article: 'Lyre' },
      { article: 'Cymbalum' },
      { article: 'Piano', group: 'clavier' },
      { article: 'Clavecin', group: 'clavier' },
      { article: 'Orgue' },
      { article: 'Synthétiseur' },
      { article: 'Accordéon', group: 'soufflet' },
      { article: 'Bandonéon', group: 'soufflet' },
      { article: 'Harmonica' },
      { article: 'Flûte traversière', group: 'flute' },
      { article: 'Piccolo', group: 'flute' },
      { article: 'Flûte à bec', group: 'bois' },
      { article: 'Clarinette', group: 'bois' },
      { article: 'Hautbois', group: 'bois' },
      { article: 'Basson' },
      { article: 'Saxophone' },
      { article: 'Trompette', group: 'cuivre' },
      { article: 'Trombone', group: 'cuivre' },
      { article: 'Cor d’harmonie', title: 'Cor d’harmonie' },
      { article: 'Tuba' },
      { article: 'Cornemuse' },
      { article: 'Didgeridoo' },
      { article: 'Flûte de Pan' },
      { article: 'Ocarina' },
      { article: 'Cor des Alpes' },
      // L'image de Wikidata est un gros plan de l'embouchure : l'instrument entier se reconnaît.
      { article: 'Shakuhachi', file: 'Flet Shakuhachi.jpg' },
      { article: 'Batterie (musique)', title: 'Batterie' },
      { article: 'Timbales (musique classique)', title: 'Timbales' },
      { article: 'Caisse claire' },
      { article: 'Djembé', group: 'tambour-main' },
      { article: 'Darbouka', group: 'tambour-main' },
      { article: 'Bongo', title: 'Bongos', group: 'tambour-main' },
      { article: 'Conga', group: 'tambour-main' },
      { article: 'Tabla' },
      { article: 'Cajón' },
      { article: 'Steelpan' },
      { article: 'Xylophone', group: 'lames' },
      { article: 'Marimba', group: 'lames' },
      { article: 'Vibraphone', group: 'lames' },
      { article: 'Glockenspiel' },
      { article: 'Triangle (instrument)', title: 'Triangle' },
      { article: 'Castagnettes' },
      { article: 'Maracas' },
      { article: 'Tambourin' },
      { article: 'Gong' },
      { article: 'Kalimba' },
      { article: 'Hang' },
      { article: 'Thérémine' },
      { article: 'Harpe celtique' },
      { article: 'Taiko' },
      { article: 'Orgue de Barbarie' },
      { article: 'Viole de gambe', group: 'famille-violon' },
      { article: 'Cornet à pistons', group: 'cuivre' },
      { article: 'Soubassophone' },
      { article: 'Euphonium' },
      { article: 'Mélodica' },
      { article: 'Clairon', group: 'cuivre' },
      { article: 'Carillon' },
      { article: 'Cithare' },
    ],
  },
  {
    slug: 'fruits-legumes',
    name: 'Fruits et légumes',
    description: 'Fruits, légumes, noix et épices des marchés du monde entier.',
    sortOrder: 9,
    subjects: [
      { article: 'Pomme' },
      { article: 'Poire' },
      { article: 'Banane' },
      { article: 'Orange (fruit)', title: 'Orange', group: 'agrume' },
      { article: 'Citron', group: 'agrume' },
      { article: 'Pamplemousse', group: 'agrume' },
      { article: 'Clémentine', group: 'agrume' },
      { article: 'Fraise' },
      { article: 'Framboise', group: 'baie' },
      { article: 'Mûre (fruit de la ronce)', title: 'Mûre', group: 'baie' },
      { article: 'Myrtille', group: 'baie' },
      { article: 'Groseille' },
      { article: 'Cerise' },
      { article: 'Raisin' },
      { article: 'Pastèque' },
      { article: 'Melon' },
      { article: 'Ananas' },
      { article: 'Mangue' },
      { article: 'Papaye' },
      { article: 'Kiwi (fruit)', title: 'Kiwi' },
      { article: 'Grenade (fruit)', title: 'Grenade' },
      { article: 'Figue' },
      { article: 'Datte' },
      { article: 'Abricot', group: 'fruit-a-noyau' },
      { article: 'Pêche (fruit)', title: 'Pêche', group: 'fruit-a-noyau' },
      { article: 'Prune' },
      { article: 'Noix de coco' },
      { article: 'Avocat (fruit)', title: 'Avocat' },
      { article: 'Litchi' },
      { article: 'Pitaya', title: 'Pitaya (fruit du dragon)' },
      { article: 'Fruit de la passion' },
      { article: 'Durian' },
      { article: 'Ramboutan' },
      { article: 'Carambole' },
      { article: 'Kaki' },
      { article: 'Nectarine', group: 'fruit-a-noyau' },
      { article: 'Mandarine', group: 'agrume' },
      { article: 'Lime (fruit)', title: 'Citron vert', group: 'agrume' },
      { article: 'Kumquat', group: 'agrume' },
      { article: 'Goyave' },
      { article: 'Mangoustanier', title: 'Mangoustan' },
      { article: 'Physalis' },
      { article: 'Coing' },
      { article: 'Rhubarbe' },
      { article: 'Tomate' },
      { article: 'Carotte' },
      // Même raison : la planche de Vilmorin cède la place à un étal de marché.
      { article: 'Pomme de terre', file: 'Au marché - pommes de terre.JPG' },
      { article: 'Patate douce' },
      { article: 'Aubergine' },
      { article: 'Courgette', group: 'courge-longue' },
      { article: 'Concombre', group: 'courge-longue' },
      { article: 'Poivron' },
      { article: 'Piment' },
      { article: 'Brocoli', group: 'chou' },
      { article: 'Chou-fleur', group: 'chou' },
      { article: 'Chou romanesco' },
      { article: 'Chou rouge' },
      { article: 'Artichaut' },
      { article: 'Asperge' },
      { article: 'Poireau' },
      { article: 'Oignon', group: 'bulbe' },
      { article: 'Ail', group: 'bulbe' },
      { article: 'Radis' },
      { article: 'Betterave' },
      { article: 'Maïs' },
      // Planche botanique au milieu de photographies : remplacée par une cosse ouverte.
      { article: 'Petit pois', file: 'Peas.jpg' },
      { article: 'Haricot vert' },
      { article: 'Champignon de Paris' },
      { article: 'Potiron' },
      { article: 'Laitue', group: 'feuille' },
      { article: 'Épinard', group: 'feuille' },
      { article: 'Céleri' },
      { article: 'Fenouil' },
      { article: 'Gingembre' },
      { article: 'Noix' },
      { article: 'Noisette' },
      { article: 'Châtaigne' },
      { article: 'Olive' },
      { article: 'Vanille' },
      { article: 'Cannelle' },
      { article: 'Cacao' },
      { article: 'Pistache' },
      { article: 'Grain de café', title: 'Café' },
      { article: 'Navet' },
      { article: 'Chou de Bruxelles', group: 'chou' },
      { article: 'Topinambour' },
      { article: 'Cornichon', group: 'courge-longue' },
    ],
  },
  {
    slug: 'champignons',
    name: 'Champignons',
    description: 'Cèpes, amanites, morilles et polypores : les champignons des bois et des marchés.',
    sortOrder: 10,
    subjects: [
      { article: 'Cèpe de Bordeaux', group: 'bolet' },
      { article: 'Bolet bai', group: 'bolet' },
      { article: 'Bolet orangé', group: 'bolet' },
      { article: 'Bolet rude', group: 'bolet' },
      { article: 'Bolet Satan', group: 'bolet' },
      { article: 'Bolet amer', group: 'bolet' },
      { article: 'Suillus granulatus', group: 'bolet' },
      { article: 'Amanite tue-mouches', group: 'amanite-rouge' },
      { article: 'Amanite phalloïde', group: 'amanite-verte' },
      { article: 'Amanite panthère', group: 'amanite-brune' },
      { article: 'Amanite des Césars', group: 'amanite-rouge' },
      { article: 'Amanite vireuse', group: 'amanite-blanche' },
      { article: 'Amanite rougissante', group: 'amanite-brune' },
      { article: 'Morille', group: 'morille' },
      { article: 'Gyromitre', group: 'morille' },
      { article: 'Truffe du Périgord', group: 'truffe' },
      { article: 'Truffe blanche d’Alba', group: 'truffe' },
      { article: 'Girolle', group: 'chanterelle' },
      { article: 'Chanterelle en tube', group: 'chanterelle' },
      { article: 'Trompette-de-la-mort', group: 'chanterelle' },
      { article: 'Pleurote en huître', group: 'pleurote' },
      { article: 'Pleurote du panicaut', group: 'pleurote' },
      { article: 'Agaric bisporus' },
      { article: 'Agaric champêtre', group: 'agaric' },
      { article: 'Agaric jaunissant', group: 'agaric' },
      { article: 'Coprin chevelu' },
      { article: 'Coprin noir d’encre' },
      { article: 'Vesse-de-loup perlée', group: 'vesse' },
      { article: 'Calvatia gigantea', group: 'vesse' },
      { article: 'Scléroderme vulgaire', group: 'vesse' },
      { article: 'Lactaire délicieux', group: 'lactaire' },
      { article: 'Lactaire poivré', group: 'lactaire' },
      { article: 'Lactaire tranquille', group: 'lactaire' },
      { article: 'Russule charbonnière', group: 'russule' },
      { article: 'Russule émétique', group: 'russule' },
      { article: 'Russule verdoyante', group: 'russule' },
      { article: 'Hydne sinué' },
      { article: 'Hydne hérisson' },
      { article: 'Polypore soufré', group: 'polypore' },
      { article: 'Amadouvier', group: 'polypore' },
      { article: 'Tramète versicolore', group: 'polypore' },
      { article: 'Fistuline hépatique', group: 'polypore' },
      { article: 'Polypore du bouleau', group: 'polypore' },
      { article: 'Ganoderme luisant', group: 'polypore' },
      { article: 'Clathre rouge' },
      { article: 'Satyre puant' },
      { article: 'Anthurus d’Archer' },
      { article: 'Coulemelle', group: 'lepiote' },
      { article: 'Lépiote déguenillée', group: 'lepiote' },
      { article: 'Armillaire couleur de miel' },
      { article: 'Pholiote changeante' },
      { article: 'Pholiote écailleuse' },
      { article: 'Marasme des Oréades' },
      { article: 'Collybie à pied velouté' },
      { article: 'Mycène pure' },
      { article: 'Psilocybe semilanceata' },
      { article: 'Cortinaire violet', group: 'cortinaire' },
      { article: 'Cortinaire couleur de rocou', group: 'cortinaire' },
      { article: 'Paxille enroulé' },
      { article: 'Clitocybe nébuleux', group: 'clitocybe' },
      { article: 'Clitocybe de l’olivier', group: 'clitocybe' },
      { article: 'Entolome livide' },
      { article: 'Tricholome équestre', group: 'tricholome' },
      { article: 'Tricholome de la Saint-Georges', group: 'tricholome' },
      { article: 'Hygrophore de mars' },
      { article: 'Hygrocybe conica' },
      { article: 'Laccaire améthyste' },
      { article: 'Pézize orangée', group: 'pezize' },
      { article: 'Pézize écarlate', group: 'pezize' },
      { article: 'Helvelle crépue', group: 'pezize' },
      { article: 'Shiitake' },
      { article: 'Grifola frondosa' },
      { article: 'Oreille-de-Judas' },
      { article: 'Trémelle mésentérique' },
      { article: 'Xylaire polymorphe' },
      { article: 'Cyathus striatus' },
      { article: 'Clavaire dorée' },
      { article: 'Rhodotus palmatus' },
      { article: 'Cordyceps' },
      { article: 'Panellus stipticus' },
      { article: 'Stereum hirsutum' },
    ],
  },
  {
    slug: 'mineraux',
    name: 'Minéraux et gemmes',
    description: 'Cristaux, pierres précieuses et roches, des gemmes de joaillerie aux minéraux de collection.',
    sortOrder: 11,
    subjects: [
      { article: 'Diamant' },
      { article: 'Rubis', group: 'corindon' },
      { article: 'Saphir', group: 'corindon' },
      { article: 'Émeraude', group: 'beryl-vert' },
      { article: 'Aigue-marine', group: 'beryl-bleu' },
      { article: 'Morganite', group: 'beryl-rose' },
      { article: 'Héliodore', group: 'beryl-jaune' },
      { article: 'Topaze' },
      { article: 'Améthyste', group: 'quartz-violet' },
      { article: 'Citrine', group: 'quartz-jaune' },
      { article: 'Quartz rose', group: 'quartz-rose' },
      { article: 'Quartz fumé', group: 'quartz-brun' },
      { article: 'Cristal de roche', group: 'quartz-clair' },
      { article: 'Grenat' },
      { article: 'Turquoise (minéral)', group: 'bleu-opaque' },
      { article: 'Lapis-lazuli', group: 'bleu-profond' },
      { article: 'Sodalite', group: 'bleu-profond' },
      { article: 'Malachite', group: 'vert-bande' },
      { article: 'Azurite', group: 'bleu-profond' },
      { article: 'Chrysocolle', group: 'vert-bande' },
      { article: 'Dioptase' },
      { article: 'Pyrite', group: 'metal-dore' },
      { article: 'Marcassite', group: 'metal-dore' },
      { article: 'Chalcopyrite', group: 'metal-dore' },
      { article: 'Hématite', group: 'metal-gris' },
      { article: 'Magnétite', group: 'metal-gris' },
      { article: 'Galène', group: 'metal-gris' },
      { article: 'Stibine', group: 'metal-gris' },
      { article: 'Bismuth' },
      { article: 'Or natif', group: 'metal-dore' },
      { article: 'Argent natif', group: 'metal-gris' },
      { article: 'Cuivre natif' },
      { article: 'Fluorine' },
      { article: 'Calcite' },
      { article: 'Aragonite' },
      { article: 'Gypse', group: 'blanc-fibreux' },
      { article: 'Sélénite', group: 'blanc-fibreux' },
      { article: 'Halite' },
      { article: 'Soufre' },
      { article: 'Barytine' },
      { article: 'Célestine' },
      { article: 'Obsidienne', group: 'roche-sombre' },
      { article: 'Basalte', group: 'roche-sombre' },
      { article: 'Granite', group: 'roche-claire' },
      { article: 'Marbre', group: 'roche-claire' },
      { article: 'Ardoise', group: 'roche-sombre' },
      { article: 'Grès', group: 'roche-claire' },
      { article: 'Silex' },
      { article: 'Pierre ponce' },
      { article: 'Ambre' },
      { article: 'Jade', group: 'vert-pierre' },
      { article: 'Néphrite', group: 'vert-pierre' },
      { article: 'Jadéite', group: 'vert-pierre' },
      { article: 'Opale' },
      { article: 'Agate', group: 'calcedoine' },
      { article: 'Onyx', group: 'calcedoine' },
      { article: 'Cornaline', group: 'calcedoine' },
      { article: 'Jaspe', group: 'calcedoine' },
      { article: 'Œil-de-tigre' },
      { article: 'Tourmaline' },
      { article: 'Péridot' },
      { article: 'Spinelle' },
      { article: 'Zircon' },
      { article: 'Tanzanite' },
      { article: 'Alexandrite' },
      { article: 'Labradorite' },
      { article: 'Amazonite' },
      { article: 'Rhodochrosite', group: 'rose-minéral' },
      { article: 'Rhodonite', group: 'rose-minéral' },
      { article: 'Kunzite', group: 'rose-minéral' },
      { article: 'Charoïte' },
      { article: 'Larimar' },
      { article: 'Wulfénite', group: 'orange-cristal' },
      { article: 'Vanadinite', group: 'orange-cristal' },
      { article: 'Crocoïte', group: 'orange-cristal' },
      { article: 'Réalgar', group: 'orange-cristal' },
      { article: 'Orpiment', group: 'orange-cristal' },
      { article: 'Cinabre' },
      { article: 'Cavansite' },
      { article: 'Sphalérite' },
      { article: 'Cérusite' },
      { article: 'Staurotide' },
      { article: 'Moldavite' },
      { article: 'Perle' },
      { article: 'Corail rouge' },
      { article: 'Nacre' },
      { article: 'Jais' },
    ],
  },
  {
    slug: 'fleurs',
    name: 'Fleurs',
    description: 'Roses, orchidées, lotus et fleurs sauvages des jardins et des cinq continents.',
    sortOrder: 12,
    subjects: [
      { article: 'Rose (fleur)', group: 'rosacee-fleur' },
      { article: 'Pivoine', group: 'rosacee-fleur' },
      { article: 'Camélia', group: 'rosacee-fleur' },
      { article: 'Tulipe' },
      { article: 'Tournesol' },
      { article: 'Coquelicot', group: 'rouge-simple' },
      { article: 'Anémone (plante)', group: 'rouge-simple' },
      { article: 'Lis' },
      { article: 'Amaryllis (plante)' },
      { article: 'Phalaenopsis', group: 'orchidee' },
      { article: 'Cypripedium calceolus', group: 'orchidee' },
      { article: 'Cattleya', group: 'orchidee' },
      { article: 'Vanda', group: 'orchidee' },
      { article: 'Nelumbo nucifera', group: 'aquatique' },
      { article: 'Nénuphar', group: 'aquatique' },
      { article: 'Victoria amazonica', group: 'aquatique' },
      { article: 'Dahlia' },
      { article: 'Chrysanthème' },
      { article: 'Zinnia' },
      { article: 'Gerbera', group: 'marguerite' },
      { article: 'Marguerite commune', group: 'marguerite' },
      { article: 'Pâquerette', group: 'marguerite' },
      { article: 'Camomille', group: 'marguerite' },
      { article: 'Narcisse jaune', group: 'narcisse' },
      { article: 'Narcisse des poètes', group: 'narcisse' },
      { article: 'Jacinthe' },
      { article: 'Crocus' },
      { article: 'Muguet de mai' },
      { article: 'Perce-neige' },
      { article: 'Violette odorante', group: 'violette' },
      { article: 'Pensée (fleur)', group: 'violette' },
      { article: 'Iris (genre végétal)' },
      { article: 'Glaïeul' },
      { article: 'Renoncule des champs' },
      { article: 'Bleuet' },
      { article: 'Lavande' },
      { article: 'Souci officinal' },
      { article: 'Capucine (plante)' },
      { article: 'Pétunia' },
      { article: 'Géranium' },
      { article: 'Bégonia' },
      { article: 'Impatiens' },
      { article: 'Fuchsia (plante)' },
      { article: 'Hortensia', group: 'arbuste-fleuri' },
      { article: 'Rhododendron', group: 'azalee' },
      { article: 'Magnolia', group: 'arbre-fleuri' },
      { article: 'Prunus serrulata', group: 'arbre-fleuri' },
      { article: 'Mimosa', group: 'arbre-fleuri' },
      { article: 'Glycine' },
      { article: 'Clématite' },
      { article: 'Chèvrefeuille' },
      { article: 'Passiflore' },
      { article: 'Hibiscus' },
      { article: 'Frangipanier' },
      { article: 'Bougainvillée' },
      { article: 'Strelitzia reginae', group: 'exotique' },
      { article: 'Heliconia', group: 'exotique' },
      { article: 'Anthurium', group: 'exotique' },
      { article: 'Protea cynaroides', group: 'exotique' },
      { article: 'Arum' },
      { article: 'Œillet' },
      { article: 'Pois de senteur' },
      { article: 'Muflier' },
      { article: 'Digitale pourpre' },
      { article: 'Delphinium' },
      { article: 'Lupin' },
      { article: 'Ancolie' },
      { article: 'Nigelle de Damas' },
      { article: 'Edelweiss' },
      { article: 'Gentiane' },
      { article: 'Myosotis' },
      { article: 'Primevère' },
      { article: 'Cyclamen' },
      { article: 'Bruyère' },
      { article: 'Chardon' },
      { article: 'Pissenlit' },
      { article: 'Trèfle' },
      { article: 'Coquelourde des jardins' },
      { article: 'Rafflesia arnoldii', group: 'geante' },
      { article: 'Amorphophallus titanum', group: 'geante' },
      { article: 'Bleuet des montagnes' },
      { article: 'Cosmos (plante)' },
      { article: 'Belle-de-nuit' },
    ],
  },
  {
    slug: 'arbres',
    name: 'Arbres et feuilles',
    description: 'Chênes, érables, oliviers et géants tropicaux : les arbres du monde et leurs silhouettes.',
    sortOrder: 13,
    subjects: [
      { article: 'Chêne pédonculé', group: 'chene' },
      { article: 'Chêne vert', group: 'chene' },
      { article: 'Chêne-liège', group: 'chene' },
      { article: 'Hêtre commun', group: 'feuillu-lisse' },
      { article: 'Charme commun', group: 'feuillu-lisse' },
      { article: 'Bouleau verruqueux', group: 'ecorce-blanche' },
      { article: 'Tremble', group: 'ecorce-blanche' },
      { article: 'Érable sycomore', group: 'erable' },
      { article: 'Érable du Japon', group: 'erable' },
      { article: 'Érable à sucre', group: 'erable' },
      { article: 'Saule pleureur' },
      { article: 'Peuplier noir' },
      { article: 'Frêne commun' },
      { article: 'Orme champêtre' },
      { article: 'Tilleul à grandes feuilles' },
      { article: 'Châtaignier commun' },
      { article: 'Noyer commun' },
      { article: 'Platane commun' },
      { article: 'Aulne glutineux' },
      { article: 'Sorbier des oiseleurs' },
      { article: 'Marronnier d’Inde' },
      { article: 'Noisetier' },
      { article: 'Sureau noir' },
      { article: 'Aubépine' },
      { article: 'Houx' },
      { article: 'Buis' },
      { article: 'Laurier-sauce' },
      { article: 'If commun', group: 'conifere-sombre' },
      { article: 'Pin sylvestre', group: 'pin' },
      { article: 'Pin parasol', group: 'pin' },
      { article: 'Pinus longaeva', group: 'pin' },
      { article: 'Épicéa commun', group: 'conifere-sombre' },
      { article: 'Sapin blanc', group: 'conifere-sombre' },
      { article: 'Mélèze d’Europe', group: 'conifere-sombre' },
      { article: 'Cèdre du Liban' },
      { article: 'Cyprès commun' },
      { article: 'Genévrier commun' },
      { article: 'Séquoia à feuilles d’if', group: 'sequoia' },
      { article: 'Araucaria araucana' },
      { article: 'Ginkgo biloba' },
      { article: 'Adansonia grandidieri', group: 'baobab' },
      { article: 'Baobab africain', group: 'baobab' },
      { article: 'Olivier' },
      { article: 'Figuier commun' },
      { article: 'Palmier dattier', group: 'palmier' },
      { article: 'Cocotier', group: 'palmier' },
      { article: 'Washingtonia', group: 'palmier' },
      { article: 'Eucalyptus' },
      { article: 'Acacia' },
      { article: 'Bambou' },
      { article: 'Cerisier', group: 'arbre-fleuri' },
      { article: 'Pommier', group: 'arbre-fruitier' },
      { article: 'Poirier commun', group: 'arbre-fruitier' },
      { article: 'Amandier', group: 'arbre-fleuri' },
      { article: 'Mûrier noir' },
      { article: 'Cognassier', group: 'arbre-fruitier' },
      { article: 'Carnegiea gigantea', group: 'desert' },
      { article: 'Yucca brevifolia', group: 'desert' },
      { article: 'Dracaena cinnabari', group: 'desert' },
      { article: 'Kapokier' },
      { article: 'Teck' },
      { article: 'Acajou' },
      { article: 'Hévéa' },
      { article: 'Manguier' },
      { article: 'Jacaranda mimosifolia' },
      { article: 'Flamboyant' },
      { article: 'Banian' },
      { article: 'Ficus religiosa' },
      { article: 'Palétuvier' },
      { article: 'Cyprès chauve' },
      { article: 'Liquidambar' },
      { article: 'Catalpa' },
      { article: 'Robinier faux-acacia' },
      { article: 'Sophora du Japon' },
      { article: 'Micocoulier de Provence' },
      { article: 'Arbousier' },
      { article: 'Cormier' },
      { article: 'Alisier torminal' },
      { article: 'Érable champêtre', group: 'erable' },
      { article: 'Pin de Wollemi' },
      { article: 'Metasequoia glyptostroboides', group: 'sequoia' },
    ],
  },
  {
    slug: 'cuisine',
    name: 'Cuisine du monde',
    description: 'Sushis, paella, couscous, tacos : les plats emblématiques des cuisines du monde.',
    sortOrder: 14,
    subjects: [
      { article: 'Sushi', group: 'riz-japon' },
      { article: 'Sashimi', group: 'riz-japon' },
      { article: 'Onigiri', group: 'riz-japon' },
      { article: 'Ramen', group: 'nouilles-bouillon' },
      { article: 'Phở', group: 'nouilles-bouillon' },
      { article: 'Soupe udon', group: 'nouilles-bouillon' },
      { article: 'Pad thaï', group: 'nouilles-sautees' },
      { article: 'Yakitori' },
      { article: 'Tempura' },
      { article: 'Okonomiyaki' },
      { article: 'Dim sum' },
      { article: 'Canard laqué de Pékin' },
      { article: 'Mapo doufu' },
      { article: 'Rouleau de printemps' },
      { article: 'Bibimbap' },
      { article: 'Kimchi' },
      { article: 'Bulgogi' },
      { article: 'Curry' },
      { article: 'Biryani', group: 'riz-epice' },
      { article: 'Naan', group: 'pain-plat' },
      { article: 'Samoussa' },
      { article: 'Poulet tandoori' },
      { article: 'Houmous', group: 'puree-pois' },
      { article: 'Falafel' },
      { article: 'Chakchouka' },
      { article: 'Taboulé' },
      { article: 'Couscous', group: 'semoule' },
      { article: 'Tajine' },
      { article: 'Chorba' },
      { article: 'Pastilla' },
      { article: 'Kebab' },
      { article: 'Moussaka', group: 'gratin' },
      { article: 'Souvláki' },
      { article: 'Tzatzíki' },
      { article: 'Dolma' },
      { article: 'Paella', group: 'riz-epice' },
      { article: 'Tortilla de patatas' },
      { article: 'Gaspacho' },
      { article: 'Tapas' },
      { article: 'Jambon ibérique' },
      { article: 'Pizza' },
      { article: 'Spaghetti', group: 'pates' },
      { article: 'Lasagnes', group: 'gratin' },
      { article: 'Risotto' },
      { article: 'Gnocchi', group: 'pates' },
      { article: 'Tiramisu', group: 'dessert-creme' },
      { article: 'Gelato' },
      { article: 'Panettone', group: 'patisserie-levee' },
      { article: 'Ratatouille' },
      { article: 'Bouillabaisse', group: 'soupe-poisson' },
      { article: 'Cassoulet' },
      { article: 'Quiche lorraine' },
      { article: 'Croissant', group: 'viennoiserie' },
      { article: 'Baguette (pain)', group: 'pain' },
      { article: 'Crêpe', group: 'galette' },
      { article: 'Macaron', group: 'petit-four' },
      { article: 'Éclair (pâtisserie)', group: 'petit-four' },
      { article: 'Mille-feuille', group: 'petit-four' },
      { article: 'Fondue savoyarde', group: 'fromage-fondu' },
      { article: 'Raclette', group: 'fromage-fondu' },
      { article: 'Choucroute' },
      { article: 'Bretzel', group: 'pain' },
      { article: 'Currywurst' },
      { article: 'Strudel', group: 'patisserie-levee' },
      { article: 'Forêt-Noire (gâteau)', group: 'dessert-creme' },
      { article: 'Goulash', group: 'ragout' },
      { article: 'Bortsch', group: 'soupe-rouge' },
      { article: 'Pierogi' },
      { article: 'Blini', group: 'galette' },
      { article: 'Caviar' },
      { article: 'Fish and chips' },
      { article: 'Rosbif' },
      { article: 'Scone' },
      { article: 'Haggis' },
      { article: 'Pudding' },
      { article: 'Smørrebrød' },
      { article: 'Gravlax' },
      { article: 'Poutine (cuisine)' },
      { article: 'Hamburger' },
      { article: 'Hot-dog' },
      { article: 'Bagel', group: 'pain' },
      { article: 'Cheesecake', group: 'dessert-creme' },
      { article: 'Beignet américain' },
      { article: 'Pancake', group: 'galette' },
      { article: 'Taco', group: 'galette-mais' },
      { article: 'Guacamole', group: 'puree-pois' },
      { article: 'Burrito', group: 'galette-mais' },
      { article: 'Enchilada', group: 'galette-mais' },
      { article: 'Ceviche' },
      { article: 'Empanada' },
      { article: 'Asado' },
      { article: 'Feijoada', group: 'ragout' },
      { article: 'Injera' },
      { article: 'Baklava', group: 'petit-four' },
      { article: 'Loukoum' },
      { article: 'Churros' },
      { article: 'Pavlova (cuisine)' },
    ],
  },
  {
    slug: 'vehicules',
    name: 'Véhicules de légende',
    description: 'Automobiles, trains, avions et navires entrés dans l’histoire, de la Coccinelle au Concorde.',
    sortOrder: 15,
    subjects: [
      { article: 'Volkswagen Coccinelle', group: 'petite-populaire' },
      { article: 'Citroën 2 CV', group: 'petite-populaire' },
      { article: 'Fiat 500', group: 'petite-populaire' },
      { article: 'Mini (BMC)', group: 'petite-populaire' },
      { article: 'Renault 4', group: 'petite-populaire' },
      { article: 'Citroën DS' },
      { article: 'Citroën Traction Avant' },
      { article: 'Peugeot 205' },
      { article: 'Renault Espace' },
      { article: 'Ford T' },
      { article: 'Ford Mustang', group: 'muscle-car' },
      { article: 'Chevrolet Corvette', group: 'muscle-car' },
      { article: 'Cadillac Eldorado', group: 'americaine-chrome' },
      { article: 'Chevrolet Bel Air', group: 'americaine-chrome' },
      { article: 'Jeep Willys', group: 'tout-terrain' },
      { article: 'Land Rover Defender', group: 'tout-terrain' },
      { article: 'Lada Niva', group: 'tout-terrain' },
      { article: 'Porsche 911', group: 'sportive' },
      { article: 'Ferrari 250 GTO', group: 'sportive' },
      { article: 'Lamborghini Miura', group: 'sportive' },
      { article: 'Jaguar Type E', group: 'sportive' },
      { article: 'Aston Martin DB5', group: 'sportive' },
      { article: 'Mercedes-Benz 300 SL', group: 'sportive' },
      { article: 'Bugatti Veyron', group: 'supercar' },
      { article: 'McLaren F1', group: 'supercar' },
      { article: 'DeLorean DMC-12' },
      { article: 'Trabant' },
      { article: 'Volkswagen Combi' },
      { article: 'Rolls-Royce Phantom' },
      { article: 'Tesla Model S' },
      { article: 'Toyota Corolla' },
      { article: 'Hummer' },
      { article: 'Vespa', group: 'deux-roues' },
      { article: 'Solex', group: 'deux-roues' },
      { article: 'Harley-Davidson', group: 'moto' },
      { article: 'Honda Super Cub', group: 'deux-roues' },
      { article: 'Triumph Bonneville', group: 'moto' },
      { article: 'Ducati', group: 'moto' },
      { article: 'Bicyclette', group: 'cycle' },
      { article: 'Grand-bi', group: 'cycle' },
      { article: 'Concorde (avion)', group: 'avion-ligne' },
      { article: 'Boeing 747', group: 'avion-ligne' },
      { article: 'Airbus A380', group: 'avion-ligne' },
      { article: 'Sud-Aviation Caravelle', group: 'avion-ligne' },
      { article: 'Douglas DC-3', group: 'avion-helice' },
      { article: 'Supermarine Spitfire', group: 'avion-chasse' },
      { article: 'Messerschmitt Bf 109', group: 'avion-chasse' },
      { article: 'Lockheed SR-71 Blackbird', group: 'avion-chasse' },
      { article: 'Boeing B-17 Flying Fortress', group: 'avion-helice' },
      { article: 'Wright Flyer', group: 'pionnier' },
      { article: 'Spirit of St. Louis', group: 'pionnier' },
      { article: 'Antonov An-225' },
      { article: 'LZ 129 Hindenburg', group: 'aerostat' },
      { article: 'Zeppelin', group: 'aerostat' },
      { article: 'Montgolfière', group: 'aerostat' },
      { article: 'Orient-Express', group: 'train' },
      { article: 'TGV', group: 'train-rapide' },
      { article: 'Shinkansen', group: 'train-rapide' },
      { article: 'Flying Scotsman', group: 'vapeur' },
      { article: 'Mallard (locomotive)', group: 'vapeur' },
      { article: 'Union Pacific Big Boy', group: 'vapeur' },
      { article: 'Locomotive à vapeur', group: 'vapeur' },
      { article: 'Tramway' },
      { article: 'Funiculaire' },
      { article: 'Téléphérique' },
      { article: 'Titanic', group: 'paquebot' },
      { article: 'Queen Mary 2', group: 'paquebot' },
      { article: 'Cutty Sark', group: 'voilier' },
      { article: 'Hermione (1779)', group: 'voilier' },
      { article: 'Santa María (navire)', group: 'voilier' },
      { article: 'Drakkar', group: 'voilier' },
      { article: 'Gondole (bateau)' },
      { article: 'Jonque' },
      { article: 'Felouque' },
      { article: 'Pirogue' },
      { article: 'Sous-marin' },
      { article: 'Brise-glace' },
      { article: 'Hovercraft' },
      { article: 'Tuk-tuk' },
      { article: 'Pousse-pousse' },
      { article: 'Traîneau à chiens' },
      { article: 'Segway' },
      { article: 'Autobus à impériale' },
      { article: 'Taxi new-yorkais' },
    ],
  },
  {
    slug: 'sports',
    name: 'Sports',
    description: 'Ballons, tatamis, pistes et sommets : les disciplines sportives en action.',
    sortOrder: 16,
    subjects: [
      { article: 'Football', group: 'ballon-terrain' },
      { article: 'Football américain', group: 'ballon-terrain' },
      { article: 'Rugby à XV', group: 'ballon-ovale' },
      { article: 'Rugby à XIII', group: 'ballon-ovale' },
      { article: 'Basket-ball' },
      { article: 'Handball', group: 'salle-but' },
      { article: 'Volley-ball', group: 'salle-filet' },
      { article: 'Tennis', group: 'raquette' },
      { article: 'Badminton', group: 'raquette' },
      { article: 'Tennis de table', group: 'raquette' },
      { article: 'Squash', group: 'raquette' },
      { article: 'Golf' },
      { article: 'Baseball' },
      { article: 'Cricket' },
      { article: 'Hockey sur glace', group: 'hockey' },
      { article: 'Hockey sur gazon', group: 'hockey' },
      { article: 'Escrime' },
      { article: 'Judo', group: 'arts-martiaux' },
      { article: 'Karaté', group: 'arts-martiaux' },
      { article: 'Taekwondo', group: 'arts-martiaux' },
      { article: 'Aïkido', group: 'arts-martiaux' },
      { article: 'Kendo' },
      { article: 'Lutte', group: 'corps-a-corps' },
      { article: 'Sumo' },
      { article: 'Boxe anglaise', group: 'corps-a-corps' },
      { article: 'Capoeira' },
      { article: 'Saut à la perche', group: 'athletisme-saut' },
      { article: 'Saut en hauteur', group: 'athletisme-saut' },
      { article: 'Saut en longueur', group: 'athletisme-saut' },
      { article: 'Lancer du poids', group: 'athletisme-lancer' },
      { article: 'Lancer du javelot', group: 'athletisme-lancer' },
      { article: 'Lancer du disque', group: 'athletisme-lancer' },
      { article: '110 mètres haies', group: 'course' },
      { article: 'Marathon', group: 'course' },
      { article: 'Sprint (athlétisme)', group: 'course' },
      { article: 'Triathlon' },
      { article: 'Natation', group: 'bassin' },
      { article: 'Plongeon', group: 'bassin' },
      { article: 'Water-polo', group: 'bassin' },
      { article: 'Natation synchronisée', group: 'bassin' },
      { article: 'Surf', group: 'glisse-mer' },
      { article: 'Planche à voile', group: 'glisse-mer' },
      { article: 'Kitesurf', group: 'glisse-mer' },
      { article: 'Voile (sport)', group: 'glisse-mer' },
      { article: 'Aviron (sport)', group: 'rame' },
      { article: 'Canoë-kayak', group: 'rame' },
      { article: 'Ski alpin', group: 'ski' },
      { article: 'Ski de fond', group: 'ski' },
      { article: 'Saut à ski', group: 'ski' },
      { article: 'Snowboard', group: 'ski' },
      { article: 'Patinage artistique', group: 'patinage' },
      { article: 'Patinage de vitesse', group: 'patinage' },
      { article: 'Curling' },
      { article: 'Biathlon' },
      { article: 'Bobsleigh', group: 'luge' },
      { article: 'Luge', group: 'luge' },
      { article: 'Skeleton', group: 'luge' },
      { article: 'Escalade', group: 'vertical' },
      { article: 'Alpinisme', group: 'vertical' },
      { article: 'Parapente', group: 'air' },
      { article: 'Parachutisme', group: 'air' },
      { article: 'Deltaplane', group: 'air' },
      { article: 'Plongée sous-marine' },
      { article: 'Cyclisme sur route', group: 'velo' },
      { article: 'Vélo tout terrain', group: 'velo' },
      { article: 'Bicycle motocross', group: 'velo' },
      { article: 'Cyclisme sur piste', group: 'velo' },
      { article: 'Motocross', group: 'moto-sport' },
      { article: 'Formule 1', group: 'auto-sport' },
      { article: 'Rallye automobile', group: 'auto-sport' },
      { article: 'Vitesse moto', group: 'moto-sport' },
      { article: 'Équitation', group: 'cheval' },
      { article: 'Saut d’obstacles', group: 'cheval' },
      { article: 'Dressage', group: 'cheval' },
      { article: 'Polo', group: 'cheval' },
      { article: 'Tir à l’arc' },
      { article: 'Tir sportif' },
      { article: 'Haltérophilie' },
      { article: 'Gymnastique artistique', group: 'gym' },
      { article: 'Gymnastique rythmique', group: 'gym' },
      { article: 'Trampoline', group: 'gym' },
      { article: 'Skateboard' },
      { article: 'Roller' },
      { article: 'Pétanque' },
      { article: 'Bowling' },
      { article: 'Fléchettes' },
      { article: 'Billard' },
      { article: 'Pelote basque' },
      { article: 'Hurling' },
      { article: 'Kabaddi' },
      { article: 'Sepak takraw' },
      { article: 'Crosse (sport)' },
      { article: 'Escalade de bloc', group: 'vertical' },
    ],
  },
  {
    slug: 'costumes',
    name: 'Costumes traditionnels',
    description: 'Kimono, sari, kilt, boubou : les vêtements traditionnels des peuples du monde.',
    sortOrder: 17,
    subjects: [
      { article: 'Kimono', group: 'japon' },
      { article: 'Yukata', group: 'japon' },
      { article: 'Hakama', group: 'japon' },
      { article: 'Obi', group: 'japon' },
      { article: 'Geta (chausses)', group: 'chaussure' },
      { article: 'Tabi', group: 'chaussure' },
      { article: 'Hanbok' },
      { article: 'Qipao', group: 'chine' },
      { article: 'Hanfu', group: 'chine' },
      { article: 'Changshan', group: 'chine' },
      { article: 'Áo dài' },
      { article: 'Nón lá', group: 'chapeau-asie' },
      { article: 'Longyi' },
      { article: 'Sarong', group: 'drape-asie' },
      { article: 'Kebaya' },
      { article: 'Batik' },
      { article: 'Barong tagalog' },
      { article: 'Baro’t saya' },
      { article: 'Deel', group: 'asie-centrale' },
      { article: 'Chuba', group: 'asie-centrale' },
      { article: 'Gho', group: 'asie-centrale' },
      { article: 'Dupatta', group: 'inde' },
      { article: 'Sari', group: 'inde' },
      { article: 'Salwar kameez', group: 'inde' },
      { article: 'Sherwani', group: 'inde' },
      { article: 'Dhoti', group: 'inde' },
      { article: 'Lehenga', group: 'inde' },
      { article: 'Turban', group: 'couvre-chef' },
      { article: 'Keffieh', group: 'couvre-chef' },
      { article: 'Fez (coiffure)', group: 'couvre-chef' },
      { article: 'Dishdasha', group: 'robe-arabe' },
      { article: 'Abaya', group: 'robe-arabe' },
      { article: 'Kaftan', group: 'robe-arabe' },
      { article: 'Djellaba', group: 'robe-arabe' },
      { article: 'Burnous' },
      { article: 'Haïk' },
      { article: 'Chèche' },
      { article: 'Boubou', group: 'afrique' },
      { article: 'Dashiki', group: 'afrique' },
      { article: 'Kente', group: 'afrique' },
      { article: 'Kanga', group: 'afrique' },
      { article: 'Bogolan' },
      { article: 'Kilt', group: 'europe-nord' },
      { article: 'Tartan', group: 'europe-nord' },
      { article: 'Bunad', group: 'europe-nord' },
      { article: 'Lusekofte' },
      { article: 'Lederhose', group: 'alpes' },
      { article: 'Dirndl', group: 'alpes' },
      { article: 'Sarafane', group: 'slave' },
      { article: 'Kokochnik', group: 'slave' },
      { article: 'Vychyvanka', group: 'slave' },
      { article: 'Costume breton', group: 'france' },
      { article: 'Coiffe bigoudène', group: 'france' },
      { article: 'Costume alsacien', group: 'france' },
      { article: 'Sabot (chaussure)', group: 'chaussure' },
      { article: 'Béret', group: 'couvre-chef' },
      { article: 'Poncho', group: 'ameriques' },
      { article: 'Chullo', group: 'ameriques' },
      { article: 'Huipil', group: 'ameriques' },
      { article: 'Rebozo', group: 'ameriques' },
      { article: 'Sombrero', group: 'chapeau-ameriques' },
      { article: 'Charro' },
      { article: 'Guayabera' },
      { article: 'Mocassin', group: 'chaussure' },
      { article: 'Coiffe amérindienne' },
      { article: 'Parka' },
      { article: 'Anorak' },
      { article: 'Fustanelle' },
      { article: 'Opinga', group: 'chaussure' },
      { article: 'Sarape', group: 'ameriques' },
      { article: 'Toge' },
      { article: 'Péplos' },
      { article: 'Chiton' },
      { article: 'Jinbei', group: 'japon' },
      { article: 'Happi', group: 'japon' },
      { article: 'Zōri', group: 'chaussure' },
      { article: 'Waraji', group: 'chaussure' },
      { article: 'Churidar', group: 'inde' },
      { article: 'Lungi', group: 'drape-asie' },
      { article: 'Pagri', group: 'couvre-chef' },
      { article: 'Gandoura', group: 'robe-arabe' },
      { article: 'Agal' },
      { article: 'Melhfa' },
      { article: 'Agbada', group: 'afrique' },
      { article: 'Pagne', group: 'afrique' },
      { article: 'Gele', group: 'couvre-chef' },
      { article: 'Himation', group: 'antique' },
      { article: 'Chlamyde', group: 'antique' },
      { article: 'Stola', group: 'antique' },
      { article: 'Tunique', group: 'antique' },
      { article: 'Kosovorotka', group: 'slave' },
      { article: 'Chapka', group: 'couvre-chef' },
      { article: 'Papakha', group: 'couvre-chef' },
      { article: 'Kalpak', group: 'couvre-chef' },
      { article: 'Sporran' },
      { article: 'Espadrille', group: 'chaussure' },
      { article: 'Charentaise', group: 'chaussure' },
      { article: 'Hennin', group: 'couvre-chef' },
      { article: 'Cornette (coiffe)', group: 'couvre-chef' },
      { article: 'Corset' },
      { article: 'Crinoline' },
      { article: 'Sarrau' },
      { article: 'Bleu de travail' },
      { article: 'Ruana', group: 'ameriques' },
      { article: 'Amauti' },
      { article: 'Kamik', group: 'chaussure' },
    ],
  },
];
