/**
 * Sujets des catégories de lancement (H-3). Chaque sujet désigne un article de
 * fr.wikipedia ; l'image retenue est l'image principale de l'élément Wikidata
 * (propriété P18), hébergée sur Wikimedia Commons.
 *
 * § 4.1, vigilance : on écarte les œuvres dont l'auteur est mort depuis moins de
 * 70 ans (Christ Rédempteur, Atomium, pyramide du Louvre, Opéra de Sydney…).
 * `group` : sujets confondables, jamais réunis dans un même tirage (EF-3.9).
 */

export interface Subject {
  article: string;
  /** Titre affiché, par défaut l'article sans précision entre parenthèses. */
  title?: string;
  group?: string;
  /**
   * Fichier Commons imposé, à la place de l'image principale Wikidata quand celle-ci se prête mal
   * au jeu (sujet trop petit dans le cadre, panorama, gravure parmi des photographies).
   */
  file?: string;
}

export interface SubjectList {
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
  subjects: Subject[];
}

export const SUBJECT_LISTS: SubjectList[] = [
  {
    slug: 'monuments',
    name: 'Monuments',
    description: 'Monuments emblématiques du monde entier, des pyramides aux cathédrales.',
    sortOrder: 1,
    subjects: [
      { article: 'Tour Eiffel' },
      { article: 'Colisée' },
      { article: 'Taj Mahal' },
      { article: 'Grande Muraille', title: 'Grande Muraille de Chine' },
      { article: 'Pyramide de Khéops' },
      { article: 'Grand Sphinx de Gizeh' },
      { article: 'Machu Picchu' },
      { article: 'Chichén Itzá', group: 'pyramide-mesoamericaine' },
      { article: 'Pyramide du Soleil', title: 'Pyramide du Soleil (Teotihuacan)', group: 'pyramide-mesoamericaine' },
      { article: 'Angkor Vat' },
      { article: 'Parthénon' },
      { article: 'Statue de la Liberté' },
      { article: 'Big Ben' },
      { article: 'Tower Bridge' },
      { article: 'Porte de Brandebourg' },
      { article: 'Cathédrale Saint-Basile-le-Bienheureux', title: 'Cathédrale Saint-Basile' },
      { article: 'Sainte-Sophie (Constantinople)', title: 'Sainte-Sophie' },
      { article: 'Tour de Pise' },
      { article: 'Basilique Saint-Pierre' },
      { article: 'Fontaine de Trevi' },
      { article: 'Cathédrale Notre-Dame de Paris', title: 'Notre-Dame de Paris', group: 'cathedrale-gothique' },
      { article: 'Cathédrale de Cologne', group: 'cathedrale-gothique' },
      { article: 'Cathédrale de Milan', group: 'cathedrale-gothique' },
      { article: "Arc de triomphe de l'Étoile", title: 'Arc de triomphe' },
      { article: 'Mont-Saint-Michel' },
      { article: 'Château de Versailles', group: 'palais-baroque' },
      { article: 'Château de Schönbrunn', group: 'palais-baroque' },
      { article: 'Château de Chambord', group: 'chateau-renaissance' },
      { article: 'Château de Chenonceau', group: 'chateau-renaissance' },
      { article: 'Pont du Gard' },
      { article: 'Basilique du Sacré-Cœur de Montmartre', title: 'Sacré-Cœur de Montmartre' },
      { article: 'Château de Neuschwanstein' },
      { article: 'Alhambra (Grenade)', title: 'Alhambra' },
      { article: 'Stonehenge' },
      { article: 'Al-Khazneh', title: 'Al-Khazneh (Pétra)' },
      { article: "Temples d'Abou Simbel", title: 'Abou Simbel' },
      { article: 'Temple de Karnak' },
      { article: 'Cité interdite' },
      { article: 'Temple du Ciel' },
      { article: 'Borobudur' },
      { article: 'Moaï', title: 'Moaï de l’île de Pâques' },
      { article: 'Kinkaku-ji' },
      { article: 'Château de Himeji' },
      { article: 'Itsukushima-jinja', title: 'Sanctuaire d’Itsukushima' },
      { article: 'Palais du Potala' },
      { article: 'Pagode Shwedagon' },
      { article: 'Harmandir Sahib', title: 'Temple d’Or d’Amritsar' },
      { article: 'Qutb Minar' },
      { article: 'Hawa Mahal' },
      { article: 'Wat Arun' },
      { article: 'Tikal' },
      { article: 'Grande mosquée de Djenné' },
      { article: 'Bete Giyorgis', title: 'Église Saint-Georges de Lalibela' },
      // Image principale Wikidata : un panorama, trop bas une fois réduit ; vue d'ensemble à la place.
      { article: 'Cité de Carcassonne', file: 'Carcassonne La Cité Vue n°3.jpg' },
      { article: 'Palais des papes d\'Avignon', title: 'Palais des papes' },
      { article: 'Abbaye de Westminster' },
      { article: "Château d'Édimbourg" },
      { article: 'Pont Charles' },
      { article: 'Parlement hongrois' },
      { article: 'Tour de Belém' },
      { article: 'Aqueduc de Ségovie' },
      { article: 'Mosquée-cathédrale de Cordoue' },
      { article: 'Palais des Doges' },
      { article: 'Pont du Rialto' },
      { article: 'Cathédrale Santa Maria del Fiore', title: 'Cathédrale de Florence' },
      { article: 'Capitole des États-Unis' },
      { article: 'Maison-Blanche' },
      { article: 'Golden Gate Bridge' },
      { article: 'Château Frontenac' },
      { article: 'Persépolis' },
      { article: 'Régistan (Samarcande)', title: 'Régistan de Samarcande' },
      { article: 'Dôme du Rocher' },
      { article: 'Chrysler Building' },
      { article: 'Tour de Londres' },
    ],
  },
  {
    slug: 'histoire',
    name: 'Histoire',
    description: 'Personnages, œuvres et objets qui ont marqué l’histoire.',
    sortOrder: 2,
    subjects: [
      { article: 'La Joconde' },
      { article: 'Vénus de Milo', group: 'statue-marbre' },
      { article: 'Victoire de Samothrace' },
      { article: 'Pierre de Rosette' },
      { article: 'Masque funéraire de Toutânkhamon', title: 'Masque de Toutânkhamon' },
      { article: 'Buste de Néfertiti' },
      { article: 'Tapisserie de Bayeux' },
      { article: 'Armée de terre cuite' },
      { article: 'Code de Hammurabi' },
      { article: 'Grotte de Lascaux' },
      { article: 'Vénus de Willendorf' },
      { article: 'Discobole' },
      { article: 'Groupe du Laocoon', title: 'Laocoon' },
      { article: 'David (Michel-Ange)', title: 'David de Michel-Ange', group: 'statue-marbre' },
      { article: 'Casque de Sutton Hoo' },
      { article: 'Figurines de Lewis', title: 'Pièces d’échecs de Lewis' },
      { article: 'La Liberté guidant le peuple' },
      { article: 'Le Radeau de La Méduse' },
      { article: 'Bonaparte franchissant le Grand-Saint-Bernard', group: 'napoleon' },
      { article: 'Le Sacre de Napoléon', group: 'napoleon' },
      { article: 'Napoléon dans son cabinet de travail', group: 'napoleon' },
      { article: 'La Cène (Léonard de Vinci)', title: 'La Cène' },
      { article: "La Création d'Adam" },
      { article: 'La Jeune Fille à la perle' },
      { article: 'La Ronde de nuit' },
      { article: 'La Nuit étoilée (1889)', title: 'La Nuit étoilée' },
      { article: 'La Naissance de Vénus (Botticelli)', title: 'La Naissance de Vénus' },
      { article: "L'École d'Athènes" },
      { article: 'Les Ménines' },
      { article: 'Tres de mayo', title: 'Tres de mayo (Goya)' },
      { article: 'La Grande Vague de Kanagawa' },
      { article: 'Le Cri' },
      { article: 'Magna Carta' },
      { article: 'Bible de Gutenberg' },
      { article: 'Livre de Kells' },
      { article: "Machine d'Anticythère" },
      { article: 'Disque céleste de Nebra' },
      { article: "Porte d'Ishtar" },
      { article: "Étendard d'Ur" },
      { article: 'Têtes colossales olmèques' },
      { article: 'Pierre du Soleil', title: 'Pierre du Soleil aztèque' },
      { article: "Masque d'Agamemnon" },
      { article: 'Aurige de Delphes' },
      { article: 'Louve du Capitole' },
      { article: 'Auguste de Prima Porta', group: 'statue-marbre' },
      { article: 'Portrait de Louis XIV en costume de sacre', title: 'Louis XIV en costume de sacre' },
      { article: "Le Portrait de l'Armada", title: 'Élisabeth Ire (portrait de l’Armada)' },
      { article: "Jeanne d'Arc au sacre du roi Charles VII", title: 'Jeanne d’Arc (Ingres)' },
      { article: 'Portrait de Marie-Antoinette à la rose', title: 'Marie-Antoinette à la rose' },
      { article: 'George Washington (Lansdowne Portrait)', title: 'George Washington (portrait Lansdowne)' },
      { article: 'Abraham Lincoln' },
      { article: 'Victoria (reine du Royaume-Uni)', title: 'Reine Victoria' },
      { article: 'Albert Einstein' },
      { article: 'Marie Curie' },
      { article: 'Mohandas Karamchand Gandhi', title: 'Gandhi' },
      { article: 'Léonard de Vinci' },
      { article: 'Galilée (savant)', title: 'Galilée' },
      { article: 'Isaac Newton' },
      { article: 'William Shakespeare' },
      { article: 'Molière' },
      { article: 'Victor Hugo' },
      { article: 'Wolfgang Amadeus Mozart', title: 'Mozart' },
      { article: 'Ludwig van Beethoven', title: 'Beethoven' },
      { article: "Mosaïque d'Alexandre" },
      { article: "Bateau d'Oseberg" },
      { article: 'Liberty Bell', title: 'Cloche de la Liberté' },
      { article: 'Couronne de saint Édouard' },
      { article: 'Enigma (machine)', title: 'Machine Enigma' },
      { article: 'Wright Flyer' },
      { article: 'Titanic (paquebot)', title: 'Titanic' },
      { article: "La Déclaration d'indépendance (Trumbull)", title: 'La Déclaration d’indépendance (Trumbull)' },
    ],
  },
  {
    slug: 'faune',
    name: 'Faune',
    description: 'Animaux des cinq continents et des océans.',
    sortOrder: 4,
    subjects: [
      { article: 'Lion' },
      { article: 'Tigre' },
      { article: 'Léopard', group: 'felin-tachete' },
      { article: 'Jaguar', group: 'felin-tachete' },
      { article: 'Guépard', group: 'felin-tachete' },
      { article: "Éléphant de savane d'Afrique", title: 'Éléphant d’Afrique' },
      { article: 'Girafe' },
      { article: 'Zèbre des plaines', title: 'Zèbre' },
      { article: 'Rhinocéros blanc' },
      { article: 'Hippopotame amphibie', title: 'Hippopotame' },
      { article: 'Gorille' },
      { article: 'Chimpanzé commun', title: 'Chimpanzé' },
      { article: 'Orang-outan' },
      { article: 'Kangourou roux', title: 'Kangourou' },
      { article: 'Koala' },
      { article: 'Panda géant' },
      { article: 'Petit panda' },
      { article: 'Flamant rose' },
      { article: 'Paon bleu', title: 'Paon' },
      { article: 'Pygargue à tête blanche' },
      { article: 'Harfang des neiges' },
      { article: 'Toucan toco', title: 'Toucan' },
      { article: 'Ara macao' },
      { article: 'Colibri à gorge rubis', title: 'Colibri' },
      { article: 'Macareux moine' },
      { article: "Autruche d'Afrique", title: 'Autruche' },
      { article: 'Manchot empereur' },
      { article: 'Grand dauphin', title: 'Dauphin' },
      { article: 'Orque' },
      { article: 'Baleine à bosse' },
      { article: 'Grand requin blanc', title: 'Requin blanc' },
      { article: 'Tortue verte', title: 'Tortue marine' },
      // Image principale Wikidata : une gravure, seule parmi des photographies.
      {
        article: 'Poulpe commun',
        title: 'Pieuvre',
        file: 'Pulpo (Octopus vulgaris), isla de Mouro, Santander, España, 2019-08-14, DD 30.jpg',
      },
      { article: 'Amphiprion ocellaris', title: 'Poisson-clown' },
      { article: 'Hippocampe (poisson)', title: 'Hippocampe' },
      { article: 'Caméléon panthère', title: 'Caméléon' },
      { article: 'Crocodile du Nil', title: 'Crocodile' },
      { article: 'Dragon de Komodo' },
      { article: 'Rainette aux yeux rouges' },
      // Image principale Wikidata : serpent trop petit dans le cadre pour une carte ; tête en gros plan.
      { article: 'Cobra royal', file: 'Ophiophagus hannah head.jpg' },
      { article: 'Tortue géante des Galápagos' },
      { article: 'Dromadaire' },
      { article: 'Lama (animal)', title: 'Lama' },
      { article: "Bison d'Amérique", title: 'Bison' },
      { article: 'Élan', title: 'Élan (orignal)', group: 'cervide' },
      { article: 'Renne', group: 'cervide' },
      { article: 'Loup gris', title: 'Loup' },
      { article: 'Renard roux', group: 'renard' },
      { article: 'Renard polaire', group: 'renard' },
      { article: 'Raton laveur' },
      { article: "Hérisson d'Europe", title: 'Hérisson' },
      { article: 'Écureuil roux' },
      { article: "Castor d'Europe", title: 'Castor' },
      { article: 'Bradypus variegatus', title: 'Paresseux à trois doigts', group: 'paresseux' },
      { article: 'Tatou à neuf bandes', title: 'Tatou' },
      { article: 'Ornithorynque' },
      { article: 'Suricate' },
      { article: 'Maki catta' },
      { article: 'Monarque (papillon)', title: 'Papillon monarque' },
      { article: 'Abeille européenne', title: 'Abeille' },
      { article: 'Coccinelle à sept points', title: 'Coccinelle' },
      { article: 'Ours brun' },
      { article: 'Ours blanc' },
      { article: 'Morse (animal)', title: 'Morse' },
      { article: 'Loutre de mer' },
      { article: 'Lynx boréal', title: 'Lynx' },
      { article: 'Axolotl' },
      { article: 'Paresseux à deux doigts', title: 'Paresseux à deux doigts', group: 'paresseux' },
      { article: 'Chouette effraie', title: 'Chouette effraie' },
      { article: 'Pélican brun', title: 'Pélican' },
      { article: 'Mouffette rayée', title: 'Mouffette' },
    ],
  },
  {
    slug: 'espace',
    name: 'Espace',
    description: 'Planètes, lunes, nébuleuses, galaxies et missions spatiales, en images de la NASA, de l’ESA et de Commons.',
    sortOrder: 5,
    subjects: [
      { article: 'Soleil' },
      { article: 'Mercure (planète)', group: 'astre-cratere' },
      { article: 'Vénus (planète)' },
      { article: 'Terre' },
      { article: 'Mars (planète)' },
      { article: 'Jupiter (planète)' },
      { article: 'Saturne (planète)' },
      { article: 'Uranus (planète)', group: 'geante-de-glace' },
      { article: 'Neptune (planète)', group: 'geante-de-glace' },
      { article: 'Pluton (planète naine)' },
      { article: 'Cérès (planète naine)', group: 'astre-cratere' },
      { article: 'Lune', group: 'astre-cratere' },
      { article: 'Io (lune)' },
      { article: 'Europe (lune)', group: 'lune-glacee' },
      { article: 'Ganymède (lune)', group: 'lune-glacee' },
      { article: 'Callisto (lune)', group: 'astre-cratere' },
      { article: 'Titan (lune)' },
      { article: 'Encelade (lune)', group: 'lune-glacee' },
      { article: 'Phobos (lune)' },
      { article: 'Grande Tache rouge' },
      { article: 'Olympus Mons' },
      { article: 'Valles Marineris' },
      { article: 'Comète de Halley', group: 'comete' },
      { article: 'C/1995 O1 (Hale-Bopp)', title: 'Comète Hale-Bopp', group: 'comete' },
      { article: 'Aurore polaire' },
      { article: 'Éclipse solaire' },
      { article: 'Meteor Crater' },
      { article: 'Voie lactée' },
      { article: 'Galaxie d’Andromède', group: 'galaxie-spirale' },
      { article: 'Galaxie du Tourbillon', group: 'galaxie-spirale' },
      { article: 'Galaxie du Triangle', group: 'galaxie-spirale' },
      { article: 'Galaxie du Sombrero' },
      { article: 'Grand Nuage de Magellan' },
      { article: 'Quintette de Stephan' },
      { article: 'Pléiades (astronomie)', title: 'Pléiades' },
      { article: 'Omega Centauri', title: 'Oméga du Centaure' },
      { article: 'Nébuleuse du Crabe' },
      { article: 'Nébuleuse d’Orion', group: 'nebuleuse-diffuse' },
      { article: 'Piliers de la création' },
      { article: 'Nébuleuse de la Carène', group: 'nebuleuse-diffuse' },
      { article: 'Nébuleuse de la Tête de Cheval' },
      { article: 'Nébuleuse de la Rosette', group: 'nebuleuse-diffuse' },
      { article: "Nébuleuse de l'Hélice", title: 'Nébuleuse de l’Hélice', group: 'nebuleuse-planetaire' },
      { article: "Nébuleuse de l'Œil de chat", title: 'Nébuleuse de l’Œil de chat', group: 'nebuleuse-planetaire' },
      { article: 'Nébuleuse de la Lyre', group: 'nebuleuse-planetaire' },
      { article: 'Cassiopeia A' },
      { article: 'Sagittarius A*', title: 'Trou noir de la Voie lactée' },
      { article: 'La Bille bleue', title: 'La Bille bleue (Apollo 17)' },
      { article: 'Lever de Terre' },
      { article: 'Spoutnik 1' },
      { article: 'Vostok 1' },
      { article: 'Apollo 11' },
      { article: 'Module lunaire Apollo' },
      { article: 'Lunar Roving Vehicle', title: 'Jeep lunaire', group: 'rover' },
      // Image principale Wikidata : sept fusées côte à côte, illisibles sur une carte ; un seul décollage.
      { article: 'Saturn V', group: 'fusee', file: 'Apollo 11 Launch - GPN-2000-000630.jpg' },
      { article: 'Ariane 5', group: 'fusee' },
      { article: 'Falcon 9', group: 'fusee' },
      { article: 'Navette spatiale américaine', title: 'Navette spatiale' },
      { article: 'Station spatiale internationale' },
      { article: 'Mir (station spatiale)', title: 'Station Mir' },
      { article: 'Skylab' },
      { article: 'Télescope spatial Hubble' },
      { article: 'Télescope spatial James-Webb' },
      { article: 'Voyager 1', group: 'sonde' },
      { article: 'Cassini-Huygens', group: 'sonde' },
      { article: 'New Horizons', group: 'sonde' },
      { article: 'Rosetta (sonde spatiale)', title: 'Rosetta', group: 'sonde' },
      { article: 'Curiosity (rover)', title: 'Curiosity', group: 'rover' },
      { article: 'Perseverance (rover)', title: 'Perseverance', group: 'rover' },
      { article: 'Opportunity (rover)', title: 'Opportunity', group: 'rover' },
      { article: 'Iouri Gagarine', title: 'Youri Gagarine' },
      { article: 'Valentina Terechkova' },
      { article: 'Neil Armstrong', group: 'astronaute-apollo' },
      { article: 'Buzz Aldrin', group: 'astronaute-apollo' },
      { article: 'Sally Ride' },
      { article: "Radiotélescope d'Arecibo", title: 'Radiotélescope d’Arecibo' },
      { article: 'Very Large Telescope' },
      { article: 'Centre spatial guyanais' },
    ],
  },
];
